title: AI Projects con LLMs, RAG, Gradio, Langchain, Chroma, Hugging Face
theme: jekyll-theme-cayman

# Enlace al CSS personalizado
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: "/assets/css/custom.css"
