title: "Mi sitio con Cayman"
description: "Un sitio web hermoso con Jekyll y el tema Cayman"
baseurl: "" # Si tu sitio está en un subdirectorio, pon algo como "/blog"
url: "https://www.misitio.com"  # Aquí va tu URL principal

# Configuración del tema Cayman
theme: "jekyll-theme-cayman"

# Menú de navegación
menu:
  - title: "Inicio"
    url: "/"
  - title: "Acerca de"
    url: "/acerca"
  - title: "Servicios"
    url: "/servicios"
  - title: "Contacto"
    url: "/contacto"


