title: Proyectos de IA - fmmarco29
description: Aplicaciones de IA prácticas y desplegables
theme: jekyll-theme-cayman
theme_color:
  primary:'#3498db'
  secondary:'#f1c40f'
baseurl: ""
url: "https://fmmarco29.github.io"  
font-family: "Open Sans", sans-serif
markdown: kramdown
plugins:
  - jekyll-feed
