title: Proyectos de IA - fmmarco29
description: Aplicaciones de IA prácticas y desplegables
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

menu:
  - title: "Inicio"
    url: "/"
  - title: "Acerca de"
    url: "/acerca"
  - title: "Contacto"
    url: "/contacto"


