# Archivo: _config.yml

title: AI Projects con LLMs, RAG, Gradio, Langchain, Chroma, Hugging Face
description: Proyectos educativos en inteligencia artificial por video, con notebooks interactivos.
theme: jekyll-theme-cayman

# Enlazar CSS personalizado
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: "/assets/css/custom.css"
