title: "Mi sitio Jekyll"
description: "Descripción de mi sitio"
baseurl: "" # Si usas un subdirectorio, coloca la URL aquí
url: "https://www.misitio.com"  # Tu URL principal

menu:
  - title: "Inicio"
    url: "/"
  - title: "Acerca de"
    url: "/acerca"
  - title: "Servicios"
    url: "/servicios"
  - title: "Contacto"
    url: "/contacto"

